name: Build README

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '40 2 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Update README
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push if changed
        run: |-
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git add README.md
          git commit -m "chore: update recent activity" || echo "No changes to commit"
          git push
